# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27a3a710f01b495727692aea6a8e0e0f7109277bd38baa6b886c9f086678f0a547429722c9c7ea3544dd5220f3d2961c7e2e15803822335566f5007f813c9a97

test:
  secret_key_base: d7a91394b1f35819825dd7dec49586a37d3f2da96da89d07033d844671c235bef056fbe17b053ff9a2d2ea06992f79b4d3fca49a3fb186ecf8b2d71f9333b154

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
